name: monetization
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  js: ^0.6.1+1
  http: ^0.12.1

dev_dependencies:
  lint: ^1.0.0
  test: ^1.14.4
