name: monetization
description: A wrapper around the Web Monetization API to monetize content.
version: 1.0.1
homepage: https://github.com/KNawm/monetization
repository: https://github.com/KNawm/monetization

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  js: ^0.6.1+1

dev_dependencies:
  test: ^1.14.4
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=2.6.1 <3.0.0"
  lint: ^0.3.0
